"""create simulation_run and tick_snapshot

Revision ID: 2e468aebb9e8
Revises: 
Create Date: 2026-06-05 16:34:27.370791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e468aebb9e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'stopped', name='run_status'), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('total_turns_configured', sa.Integer(), nullable=False),
    sa.Column('total_turns_run', sa.Integer(), nullable=False),
    sa.Column('behavior_strategy', sa.String(length=64), nullable=False),
    sa.Column('initial_population', sa.Integer(), nullable=False),
    sa.Column('board_size', sa.Integer(), nullable=False),
    sa.Column('vision_range', sa.Integer(), nullable=False),
    sa.Column('initial_energy', sa.Float(), nullable=False),
    sa.Column('max_energy', sa.Float(), nullable=False),
    sa.Column('energy_decay_per_tick', sa.Float(), nullable=False),
    sa.Column('fight_energy_cost', sa.Float(), nullable=False),
    sa.Column('reproduction_energy_cost', sa.Float(), nullable=False),
    sa.Column('reproduction_min_energy', sa.Float(), nullable=False),
    sa.Column('maturity_age', sa.Integer(), nullable=False),
    sa.Column('juvenile_max_energy_factor', sa.Float(), nullable=False),
    sa.Column('fruit_energy_value', sa.Float(), nullable=False),
    sa.Column('poison_energy_value', sa.Float(), nullable=False),
    sa.Column('resistance_reduction_per_point', sa.Float(), nullable=False),
    sa.Column('max_fruits', sa.Integer(), nullable=False),
    sa.Column('max_poisons', sa.Integer(), nullable=False),
    sa.Column('mutation_rate', sa.Float(), nullable=False),
    sa.Column('mutation_magnitude', sa.Float(), nullable=False),
    sa.Column('lifespan_min', sa.Integer(), nullable=False),
    sa.Column('lifespan_max', sa.Integer(), nullable=False),
    sa.Column('vision_range_min', sa.Integer(), nullable=False),
    sa.Column('vision_range_max', sa.Integer(), nullable=False),
    sa.Column('metabolism_min', sa.Float(), nullable=False),
    sa.Column('metabolism_max', sa.Float(), nullable=False),
    sa.Column('aggression_min', sa.Float(), nullable=False),
    sa.Column('aggression_max', sa.Float(), nullable=False),
    sa.Column('hunger_threshold_min', sa.Integer(), nullable=False),
    sa.Column('hunger_threshold_max', sa.Integer(), nullable=False),
    sa.Column('safe_threshold_min', sa.Integer(), nullable=False),
    sa.Column('safe_threshold_max', sa.Integer(), nullable=False),
    sa.Column('resistance_min', sa.Float(), nullable=False),
    sa.Column('resistance_max', sa.Float(), nullable=False),
    sa.Column('reproduction_weights', sa.JSON(), nullable=False),
    sa.Column('snapshot_enabled', sa.Boolean(), nullable=False),
    sa.Column('snapshot_interval', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tick_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('population_total', sa.Integer(), nullable=False),
    sa.Column('population_male', sa.Integer(), nullable=False),
    sa.Column('population_female', sa.Integer(), nullable=False),
    sa.Column('avg_energy', sa.Float(), nullable=False),
    sa.Column('min_energy', sa.Float(), nullable=False),
    sa.Column('max_energy', sa.Float(), nullable=False),
    sa.Column('births', sa.Integer(), nullable=False),
    sa.Column('deaths_total', sa.Integer(), nullable=False),
    sa.Column('deaths_starvation', sa.Integer(), nullable=False),
    sa.Column('deaths_age', sa.Integer(), nullable=False),
    sa.Column('deaths_fight', sa.Integer(), nullable=False),
    sa.Column('fights_total', sa.Integer(), nullable=False),
    sa.Column('reproductions_successful', sa.Integer(), nullable=False),
    sa.Column('reproductions_failed_space', sa.Integer(), nullable=False),
    sa.Column('reproductions_failed_energy', sa.Integer(), nullable=False),
    sa.Column('fruits_on_board', sa.Integer(), nullable=False),
    sa.Column('poisons_on_board', sa.Integer(), nullable=False),
    sa.Column('avg_lifespan', sa.Float(), nullable=False),
    sa.Column('avg_vision_range', sa.Float(), nullable=False),
    sa.Column('avg_metabolism', sa.Float(), nullable=False),
    sa.Column('avg_aggression', sa.Float(), nullable=False),
    sa.Column('avg_hunger_threshold', sa.Float(), nullable=False),
    sa.Column('avg_safe_threshold', sa.Float(), nullable=False),
    sa.Column('avg_resistance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tick_snapshot_simulation_id', 'tick_snapshot', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tick_snapshot_simulation_id', table_name='tick_snapshot')
    op.drop_table('tick_snapshot')
    op.drop_table('simulation_run')
    # ### end Alembic commands ###
